config/routes.rb
Rails.application.routes.draw do
  resources :cotfc_groups
  resources :subscriptions
  resources :messages
  resources :auth_tokens
  resources :invitations
  resources :attendances
  resources :events
  resources :steps
  resources :paths
  resources :group_members
  resources :groups
  resources :guardianships
  resources :family_members
  resources :families
  resources :organization_people
  resources :addresses
  resources :organizations
  resources :people
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root "rails/health#show"
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :person
  belongs_to :event
end

app/models/auth_token.rb
class AuthToken < ApplicationRecord
  belongs_to :person
end

app/models/cotfc_group.rb
class CotfcGroup < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/family.rb
class Family < ApplicationRecord
  belongs_to :address
end

app/models/family_member.rb
class FamilyMember < ApplicationRecord
  belongs_to :person
  belongs_to :family
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :created_by, polymorphic: true
  belongs_to :step
  belongs_to :event
end

app/models/group_member.rb
class GroupMember < ApplicationRecord
  belongs_to :person
  belongs_to :group
end

app/models/guardianship.rb
class Guardianship < ApplicationRecord
  belongs_to :person
  belongs_to :guardian
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :invited_by
  belongs_to :invitable, polymorphic: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :messageable, polymorphic: true
  belongs_to :parent_message
  belongs_to :sender
end

app/models/organization.rb
class Organization < ApplicationRecord
  belongs_to :parent_organization
  belongs_to :address
end

app/models/path.rb
class Path < ApplicationRecord
  belongs_to :created_by, polymorphic: true
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :address
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :path
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :person
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[ show edit update destroy ]

  # GET /groups or /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1 or /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to group_url(@group), notice: "Group was successfully created." }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: "Group was successfully updated." }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy!

    respond_to do |format|
      format.html { redirect_to groups_url, notice: "Group was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_params
      params.require(:group).permit(:name, :description, :created_by_id, :created_by_type, :step_id, :event_id, :is_private)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/paths_helper.rb
module PathsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group, class: "contents") do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :created_by_id %>
    <%= form.text_field :created_by_id, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :step_id %>
    <%= form.text_field :step_id, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :event_id %>
    <%= form.text_field :event_id, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :is_private %>
    <%= form.check_box :is_private, class: "block mt-2 h-5 w-5" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= group.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= group.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Created by:</strong>
    <%= group.created_by_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Step:</strong>
    <%= group.step_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Event:</strong>
    <%= group.event_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Is private:</strong>
    <%= group.is_private %>
  </p>

</div>

app/views/groups/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing group</h1>

  <%= render "form", group: @group %>

  <%= link_to "Show this group", @group, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to groups", groups_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/groups/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Groups" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Groups</h1>
    <%= link_to "New group", new_group_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="groups" class="min-w-full">
    <% @groups.each do |group| %>
      <%= render group %>
      <p>
        <%= link_to "Show this group", group, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/groups/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New group</h1>

  <%= render "form", group: @group %>

  <%= link_to "Back to groups", groups_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/groups/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @group %>

    <%= link_to "Edit this group", edit_group_path(@group), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to groups", groups_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this group", @group, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>