config/routes.rb
Rails.application.routes.draw do
  resources :cotfc_groups
  resources :subscriptions
  resources :messages
  resources :auth_tokens
  resources :invitations
  resources :attendances
  resources :events
  resources :steps
  resources :paths
  resources :group_members
  resources :groups
  resources :guardianships
  resources :family_members
  resources :families
  resources :organization_people
  resources :addresses
  resources :organizations
  resources :people
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root "rails/health#show"
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :person
  belongs_to :event
end

app/models/auth_token.rb
class AuthToken < ApplicationRecord
  belongs_to :person
end

app/models/cotfc_group.rb
class CotfcGroup < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/family.rb
class Family < ApplicationRecord
  belongs_to :address
end

app/models/family_member.rb
class FamilyMember < ApplicationRecord
  belongs_to :person
  belongs_to :family
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :created_by, polymorphic: true
  belongs_to :step
  belongs_to :event
end

app/models/group_member.rb
class GroupMember < ApplicationRecord
  belongs_to :person
  belongs_to :group
end

app/models/guardianship.rb
class Guardianship < ApplicationRecord
  belongs_to :person
  belongs_to :guardian
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :invited_by
  belongs_to :invitable, polymorphic: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :messageable, polymorphic: true
  belongs_to :parent_message
  belongs_to :sender
end

app/models/organization.rb
class Organization < ApplicationRecord
  belongs_to :parent_organization
  belongs_to :address
end

app/models/path.rb
class Path < ApplicationRecord
  belongs_to :created_by, polymorphic: true
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :address
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :path
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :person
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: %i[ show edit update destroy ]

  # GET /subscriptions or /subscriptions.json
  def index
    @subscriptions = Subscription.all
  end

  # GET /subscriptions/1 or /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions or /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to subscription_url(@subscription), notice: "Subscription was successfully created." }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1 or /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to subscription_url(@subscription), notice: "Subscription was successfully updated." }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1 or /subscriptions/1.json
  def destroy
    @subscription.destroy!

    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: "Subscription was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def subscription_params
      params.require(:subscription).permit(:person_id, :stripe_customer_id, :stripe_subscription_id, :status)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/paths_helper.rb
module PathsHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<%= form_with(model: subscription, class: "contents") do |form| %>
  <% if subscription.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
        <% subscription.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :person_id %>
    <%= form.text_field :person_id, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :stripe_customer_id %>
    <%= form.text_field :stripe_customer_id, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :stripe_subscription_id %>
    <%= form.text_field :stripe_subscription_id, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :status %>
    <%= form.text_field :status, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/subscriptions/_subscription.html.erb
<div id="<%= dom_id subscription %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Person:</strong>
    <%= subscription.person_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Stripe customer:</strong>
    <%= subscription.stripe_customer_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Stripe subscription:</strong>
    <%= subscription.stripe_subscription_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Status:</strong>
    <%= subscription.status %>
  </p>

</div>

app/views/subscriptions/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing subscription</h1>

  <%= render "form", subscription: @subscription %>

  <%= link_to "Show this subscription", @subscription, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to subscriptions", subscriptions_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/subscriptions/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Subscriptions" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Subscriptions</h1>
    <%= link_to "New subscription", new_subscription_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="subscriptions" class="min-w-full">
    <% @subscriptions.each do |subscription| %>
      <%= render subscription %>
      <p>
        <%= link_to "Show this subscription", subscription, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/subscriptions/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New subscription</h1>

  <%= render "form", subscription: @subscription %>

  <%= link_to "Back to subscriptions", subscriptions_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/subscriptions/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @subscription %>

    <%= link_to "Edit this subscription", edit_subscription_path(@subscription), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to subscriptions", subscriptions_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this subscription", @subscription, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>