config/routes.rb
Rails.application.routes.draw do
  resources :cotfc_groups
  resources :subscriptions
  resources :messages
  resources :auth_tokens
  resources :invitations
  resources :attendances
  resources :events
  resources :steps
  resources :paths
  resources :group_members
  resources :groups
  resources :guardianships
  resources :family_members
  resources :families
  resources :organization_people
  resources :addresses
  resources :organizations
  resources :people
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root "rails/health#show"
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :person
  belongs_to :event
end

app/models/auth_token.rb
class AuthToken < ApplicationRecord
  belongs_to :person
end

app/models/cotfc_group.rb
class CotfcGroup < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/family.rb
class Family < ApplicationRecord
  belongs_to :address
end

app/models/family_member.rb
class FamilyMember < ApplicationRecord
  belongs_to :person
  belongs_to :family
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :created_by, polymorphic: true
  belongs_to :step
  belongs_to :event
end

app/models/group_member.rb
class GroupMember < ApplicationRecord
  belongs_to :person
  belongs_to :group
end

app/models/guardianship.rb
class Guardianship < ApplicationRecord
  belongs_to :person
  belongs_to :guardian
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :invited_by
  belongs_to :invitable, polymorphic: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :messageable, polymorphic: true
  belongs_to :parent_message
  belongs_to :sender
end

app/models/organization.rb
class Organization < ApplicationRecord
  belongs_to :parent_organization
  belongs_to :address
end

app/models/path.rb
class Path < ApplicationRecord
  belongs_to :created_by, polymorphic: true
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :address
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :path
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :person
end

app/controllers/organization_people_controller.rb
class OrganizationPeopleController < ApplicationController
  before_action :set_organization_person, only: %i[ show edit update destroy ]

  # GET /organization_people or /organization_people.json
  def index
    @organization_people = OrganizationPerson.all
  end

  # GET /organization_people/1 or /organization_people/1.json
  def show
  end

  # GET /organization_people/new
  def new
    @organization_person = OrganizationPerson.new
  end

  # GET /organization_people/1/edit
  def edit
  end

  # POST /organization_people or /organization_people.json
  def create
    @organization_person = OrganizationPerson.new(organization_person_params)

    respond_to do |format|
      if @organization_person.save
        format.html { redirect_to organization_person_url(@organization_person), notice: "Organization person was successfully created." }
        format.json { render :show, status: :created, location: @organization_person }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @organization_person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organization_people/1 or /organization_people/1.json
  def update
    respond_to do |format|
      if @organization_person.update(organization_person_params)
        format.html { redirect_to organization_person_url(@organization_person), notice: "Organization person was successfully updated." }
        format.json { render :show, status: :ok, location: @organization_person }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @organization_person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organization_people/1 or /organization_people/1.json
  def destroy
    @organization_person.destroy!

    respond_to do |format|
      format.html { redirect_to organization_people_url, notice: "Organization person was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization_person
      @organization_person = OrganizationPerson.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def organization_person_params
      params.require(:organization_person).permit(:person_id, :organization_id, :title, :type)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/organization_people_helper.rb
module OrganizationPeopleHelper
end

app/helpers/paths_helper.rb
module PathsHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/organization_people/_form.html.erb
<%= form_with(model: organization_person, class: "contents") do |form| %>
  <% if organization_person.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(organization_person.errors.count, "error") %> prohibited this organization_person from being saved:</h2>

      <ul>
        <% organization_person.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :person_id %>
    <%= form.text_field :person_id, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :organization_id %>
    <%= form.text_field :organization_id, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :type %>
    <%= form.text_field :type, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/organization_people/_organization_person.html.erb
<div id="<%= dom_id organization_person %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Person:</strong>
    <%= organization_person.person_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Organization:</strong>
    <%= organization_person.organization_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= organization_person.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Type:</strong>
    <%= organization_person.type %>
  </p>

</div>

app/views/organization_people/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing organization person</h1>

  <%= render "form", organization_person: @organization_person %>

  <%= link_to "Show this organization person", @organization_person, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to organization people", organization_people_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/organization_people/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Organization people" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Organization people</h1>
    <%= link_to "New organization person", new_organization_person_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="organization_people" class="min-w-full">
    <% @organization_people.each do |organization_person| %>
      <%= render organization_person %>
      <p>
        <%= link_to "Show this organization person", organization_person, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/organization_people/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New organization person</h1>

  <%= render "form", organization_person: @organization_person %>

  <%= link_to "Back to organization people", organization_people_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/organization_people/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @organization_person %>

    <%= link_to "Edit this organization person", edit_organization_person_path(@organization_person), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to organization people", organization_people_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this organization person", @organization_person, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>