config/routes.rb
Rails.application.routes.draw do
  resources :cotfc_groups
  resources :subscriptions
  resources :messages
  resources :auth_tokens
  resources :invitations
  resources :attendances
  resources :events
  resources :steps
  resources :paths
  resources :group_members
  resources :groups
  resources :guardianships
  resources :family_members
  resources :families
  resources :organization_people
  resources :addresses
  resources :organizations
  resources :people
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root "rails/health#show"
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :person
  belongs_to :event
end

app/models/auth_token.rb
class AuthToken < ApplicationRecord
  belongs_to :person
end

app/models/cotfc_group.rb
class CotfcGroup < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/family.rb
class Family < ApplicationRecord
  belongs_to :address
end

app/models/family_member.rb
class FamilyMember < ApplicationRecord
  belongs_to :person
  belongs_to :family
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :created_by, polymorphic: true
  belongs_to :step
  belongs_to :event
end

app/models/group_member.rb
class GroupMember < ApplicationRecord
  belongs_to :person
  belongs_to :group
end

app/models/guardianship.rb
class Guardianship < ApplicationRecord
  belongs_to :person
  belongs_to :guardian
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :invited_by
  belongs_to :invitable, polymorphic: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :messageable, polymorphic: true
  belongs_to :parent_message
  belongs_to :sender
end

app/models/organization.rb
class Organization < ApplicationRecord
  belongs_to :parent_organization
  belongs_to :address
end

app/models/path.rb
class Path < ApplicationRecord
  belongs_to :created_by, polymorphic: true
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :address
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :path
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :person
end

app/controllers/auth_tokens_controller.rb
class AuthTokensController < ApplicationController
  before_action :set_auth_token, only: %i[ show edit update destroy ]

  # GET /auth_tokens or /auth_tokens.json
  def index
    @auth_tokens = AuthToken.all
  end

  # GET /auth_tokens/1 or /auth_tokens/1.json
  def show
  end

  # GET /auth_tokens/new
  def new
    @auth_token = AuthToken.new
  end

  # GET /auth_tokens/1/edit
  def edit
  end

  # POST /auth_tokens or /auth_tokens.json
  def create
    @auth_token = AuthToken.new(auth_token_params)

    respond_to do |format|
      if @auth_token.save
        format.html { redirect_to auth_token_url(@auth_token), notice: "Auth token was successfully created." }
        format.json { render :show, status: :created, location: @auth_token }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @auth_token.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /auth_tokens/1 or /auth_tokens/1.json
  def update
    respond_to do |format|
      if @auth_token.update(auth_token_params)
        format.html { redirect_to auth_token_url(@auth_token), notice: "Auth token was successfully updated." }
        format.json { render :show, status: :ok, location: @auth_token }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @auth_token.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /auth_tokens/1 or /auth_tokens/1.json
  def destroy
    @auth_token.destroy!

    respond_to do |format|
      format.html { redirect_to auth_tokens_url, notice: "Auth token was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auth_token
      @auth_token = AuthToken.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def auth_token_params
      params.require(:auth_token).permit(:person_id, :token, :expires_at)
    end
end

app/helpers/auth_tokens_helper.rb
module AuthTokensHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/paths_helper.rb
module PathsHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/auth_tokens/_auth_token.html.erb
<div id="<%= dom_id auth_token %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Person:</strong>
    <%= auth_token.person_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Token:</strong>
    <%= auth_token.token %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Expires at:</strong>
    <%= auth_token.expires_at %>
  </p>

</div>

app/views/auth_tokens/_form.html.erb
<%= form_with(model: auth_token, class: "contents") do |form| %>
  <% if auth_token.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(auth_token.errors.count, "error") %> prohibited this auth_token from being saved:</h2>

      <ul>
        <% auth_token.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :person_id %>
    <%= form.text_field :person_id, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :token %>
    <%= form.text_field :token, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :expires_at %>
    <%= form.datetime_field :expires_at, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/auth_tokens/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing auth token</h1>

  <%= render "form", auth_token: @auth_token %>

  <%= link_to "Show this auth token", @auth_token, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to auth tokens", auth_tokens_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/auth_tokens/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Auth tokens" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Auth tokens</h1>
    <%= link_to "New auth token", new_auth_token_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="auth_tokens" class="min-w-full">
    <% @auth_tokens.each do |auth_token| %>
      <%= render auth_token %>
      <p>
        <%= link_to "Show this auth token", auth_token, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/auth_tokens/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New auth token</h1>

  <%= render "form", auth_token: @auth_token %>

  <%= link_to "Back to auth tokens", auth_tokens_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/auth_tokens/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @auth_token %>

    <%= link_to "Edit this auth token", edit_auth_token_path(@auth_token), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to auth tokens", auth_tokens_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this auth token", @auth_token, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>